"""
bot/core/pr_creator.py
----------------------
Handles all GitHub API interactions for pull request creation.
Includes daily PR limit enforcement, issue commenting, and PR body generation.
"""

import time
from datetime import date
from typing import Optional

import requests
from tenacity import retry, stop_after_attempt, wait_exponential, retry_if_exception_type

from bot.core.issue_fetcher import Issue
from bot.core.ai_engine import AnalysisResult
from bot.utils.config_loader import ConfigLoader
from bot.utils.logger import BotLogger

# Markdown template for the PR body
PR_BODY_TEMPLATE = """## Summary

{pr_description}

---

## Changes Made

{fix_description}

**Modified files:**
{modified_files_list}

---

## How to Test

```bash
# Clone and test this branch
git clone {clone_url}
cd {repo_name}
git checkout {branch_name}
pip install -r requirements.txt  # if it exists
pytest
```

---

## Confidence Score

AI confidence in this fix: **{confidence_score:.0%}**

---

*🤖 This PR was automatically generated by [Contributor Bot](https://github.com). \
Please review carefully before merging.*

Closes #{issue_number}
"""

ISSUE_COMMENT_TEMPLATE = """👋 Hi! I noticed this issue and I'm attempting an automated fix.

I'll analyze the problem and open a pull request shortly with a proposed solution.

> *This is an automated message from a contributor bot. The fix will be reviewed before merging.*
"""


class PRCreatorError(Exception):
    """Raised when a PR creation operation fails."""
    pass


class PRCreator:
    """
    Creates pull requests and posts issue comments via the GitHub API.

    Responsibilities:
    - Check and enforce daily PR limits
    - Comment on issues before opening PRs
    - Build well-structured PR bodies
    - Create PRs from fork branches to upstream repos
    """

    def __init__(self, config: ConfigLoader, logger: BotLogger):
        self.config = config
        self.logger = logger
        self.token = config.require("github.token")
        self.username = config.require("github.username")
        self.api_base = config.get("github.api_base", "https://api.github.com")
        self.headers = {
            "Authorization": f"token {self.token}",
            "Accept": "application/vnd.github.v3+json",
            "Content-Type": "application/json",
            "X-GitHub-Api-Version": "2022-11-28",
        }
        self.max_prs_per_day = int(config.get("bot.max_prs_per_day", 3))

    # ------------------------------------------------------------------ #
    # Public API                                                           #
    # ------------------------------------------------------------------ #

    def check_daily_limit(self, prs_today: int) -> bool:
        """
        Check if we've hit the daily PR creation limit.

        Args:
            prs_today: Number of PRs already created today (from BotLogger stats)

        Returns:
            True if we can still create PRs, False if limit is reached
        """
        if prs_today >= self.max_prs_per_day:
            self.logger.warning(
                "daily_limit_reached",
                limit=self.max_prs_per_day,
                created_today=prs_today,
            )
            return False
        return True

    def comment_on_issue(self, issue: Issue, dry_run: bool = False) -> Optional[str]:
        """
        Post a comment on the issue indicating we're working on a fix.

        Args:
            issue: The Issue to comment on
            dry_run: If True, log but don't actually post

        Returns:
            URL of the created comment, or None on failure
        """
        if not self.config.get("bot.comment_before_pr", True):
            return None

        if dry_run:
            self.logger.info("dry_run_comment", issue_url=issue.html_url)
            return None

        url = f"{self.api_base}/repos/{issue.repo_full_name}/issues/{issue.number}/comments"
        payload = {"body": ISSUE_COMMENT_TEMPLATE}

        try:
            resp = self._post(url, payload)
            comment_url = resp.get("html_url", "")
            self.logger.info("issue_commented", comment_url=comment_url, issue_url=issue.html_url)
            return comment_url
        except PRCreatorError as e:
            # Non-fatal: failing to comment shouldn't stop the PR
            self.logger.warning("issue_comment_failed", error=str(e))
            return None

    def create_pull_request(
        self,
        issue: Issue,
        branch_name: str,
        analysis_result: AnalysisResult,
        modified_files: list[str],
        dry_run: bool = False,
    ) -> Optional[str]:
        """
        Create a pull request from the bot's fork to the upstream repo.

        Args:
            issue: The Issue being fixed
            branch_name: Source branch in the fork (e.g., "auto-fix/123")
            analysis_result: AI analysis with PR title and description
            modified_files: List of files modified by the patch
            dry_run: If True, log the PR without actually creating it

        Returns:
            URL of the created PR, or None on failure
        """
        owner, repo = issue.repo_full_name.split("/", 1)

        # Determine the default branch of the upstream repo
        head_ref = f"{self.username}:{branch_name}"
        base_branch = self._get_default_branch(issue.repo_full_name)

        # Build the PR body
        modified_list = "\n".join(f"- `{f}`" for f in modified_files)
        body = PR_BODY_TEMPLATE.format(
            pr_description=analysis_result.pr_description,
            fix_description=analysis_result.fix_description,
            modified_files_list=modified_list,
            clone_url=f"https://github.com/{issue.repo_full_name}",
            repo_name=repo,
            branch_name=branch_name,
            confidence_score=analysis_result.confidence_score,
            issue_number=issue.number,
        )

        payload = {
            "title": analysis_result.pr_title or f"fix: resolve issue #{issue.number} - {issue.title[:50]}",
            "head": head_ref,
            "base": base_branch,
            "body": body,
            "maintainer_can_modify": True,
        }

        if dry_run:
            self.logger.info(
                "dry_run_pr",
                title=payload["title"],
                head=head_ref,
                base=base_branch,
                issue_url=issue.html_url,
            )
            return f"[DRY RUN] PR would be created: {payload['title']}"

        url = f"{self.api_base}/repos/{issue.repo_full_name}/pulls"
        try:
            resp = self._post(url, payload)
            pr_url = resp.get("html_url", "")
            self.logger.info(
                "pr_created",
                pr_url=pr_url,
                title=payload["title"],
                issue_url=issue.html_url,
            )
            return pr_url
        except PRCreatorError as e:
            self.logger.error("pr_creation_failed", error=str(e), issue_url=issue.html_url)
            raise

    def check_existing_pr(self, issue: Issue, branch_name: str) -> Optional[str]:
        """
        Check if a PR already exists for this branch to avoid duplicates.

        Returns:
            PR URL if one already exists, None otherwise
        """
        url = f"{self.api_base}/repos/{issue.repo_full_name}/pulls"
        params = {
            "state": "open",
            "head": f"{self.username}:{branch_name}",
        }
        try:
            resp = requests.get(url, headers=self.headers, params=params, timeout=30)
            resp.raise_for_status()
            pulls = resp.json()
            if pulls:
                return pulls[0].get("html_url")
        except requests.RequestException as e:
            self.logger.warning("check_existing_pr_failed", error=str(e))
        return None

    # ------------------------------------------------------------------ #
    # Private Helpers                                                      #
    # ------------------------------------------------------------------ #

    def _get_default_branch(self, repo_full_name: str) -> str:
        """Fetch the default branch name of a repository."""
        url = f"{self.api_base}/repos/{repo_full_name}"
        try:
            resp = requests.get(url, headers=self.headers, timeout=30)
            resp.raise_for_status()
            return resp.json().get("default_branch", "main")
        except requests.RequestException:
            return "main"

    @retry(
        stop=stop_after_attempt(3),
        wait=wait_exponential(multiplier=2, min=4, max=30),
        retry=retry_if_exception_type(requests.RequestException),
        reraise=True,
    )
    def _post(self, url: str, payload: dict) -> dict:
        """Make an authenticated POST request to the GitHub API."""
        resp = requests.post(url, headers=self.headers, json=payload, timeout=30)

        # Handle rate limiting
        if resp.status_code == 403 and "rate limit" in resp.text.lower():
            reset_ts = int(resp.headers.get("X-RateLimit-Reset", time.time() + 60))
            sleep_secs = max(0, reset_ts - int(time.time())) + 2
            self.logger.warning("rate_limit_hit", sleeping_secs=sleep_secs)
            time.sleep(sleep_secs)
            raise requests.RequestException("Rate limit hit — retrying")

        # 422 = Unprocessable Entity (e.g., PR already exists, or no changes)
        if resp.status_code == 422:
            data = resp.json()
            raise PRCreatorError(f"GitHub API 422: {data.get('message', str(data))}")

        resp.raise_for_status()
        return resp.json()
